### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hafmed** [Sikarjan/harbour-zirkeltraining#1]
hi please who use Nemo.KeepAlive 1.1 with out get my application rejected in harbour

**Comment by Sikarjan** [comment]
Hi there,
do you have some more information for me what your actual problem is? This app is approved by Jolla. So you can use this app as an example. 
It failed the rpm validator back when I committed it but wrote in the comment section that this is used in other Jolla apps. The answer from QA was that it is a bug in the rpm validator and that it is allowed to use it.
